---
- name: Populate user
  hosts: localhost
  gather_facts: no
  tasks:
    - name: create user
      vars:
        password: "{{ lookup('password', 'credentials/' + item + ' length=12') }}"
      user:
        name: "{{ item }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
      loop: "{{ query('lines', 'cat users.txt') }}"

